spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_demo
    username: postgres
    password: "nikvitya"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    change-log: db/changelog/db.changelog-master.xml


logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      account-id: t1-account
      transaction-id: t1-transaction
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered

      account_registration: t1_demo_accounts_registration
      account_id_registered: t1_demo_accounts_registered

      transaction_registration: t1_demo_transactions_registration
      transaction_id_registered: t1_demo_transactions_registered

      metric_trace: t1_demo_metric_trace
      error_trace: t1_demo_error_trace

    listener:
      poll-timeout: 1000

  aop:
    max-execution-time: 100
