spring:
  application:
    name: t1-java-demo
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:6543/t1_demo
    username: postgres
    password: "0000"
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: public
    change-log: db/changelog/db.changelog-master.xml
security:
  token: tstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5htstrs4g434wyhser5h
  expiration: 86400000

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG
    org.apache.kafka: INFO
    org.hibernate.SQL: INFO

t1:
  scan-path: ru.t1.java.demo
  kafka:
    bootstrap:
      server: localhost:9092
    consumer:
      group-id: t1-demo
      account-id: t1-account
      transaction-id: t1-transaction
      transaction-error-id: t1-demo-transaction-error
      max.poll.records: 10
    producer:
      enable: true
    topic:
      client_registration: t1_demo_client_registration
      client_id_registered: t1_demo_client_registered

      account_registration: t1_demo_accounts_registration
      account_id_registered: t1_demo_accounts_registered

      transaction_registration: t1_demo_client_transactions
      transaction_id_registered: t1_demo_transactions_registered

      metric_trace: t1_demo_metric_trace
      error_trace: t1_demo_error_trace
      transaction_errors: t1_demo_client_transaction_errors

    listener:
      poll-timeout: 1000

  aop:
    max-execution-time: 100
  schedule:
    transaction:
      resend:
        period: 10000

track:
  errors-to-track: JsonParseException, IOException
  kafka:
    enabled: ${TRACK_KAFKA_LOG_ENABLED:true}
    bootstrap-server: localhost:9092
    data-source-error-topic: t1_demo_data_source_error
    time-limit-exceed: t1_demo_time_limit_exceed
  db:
    enabled: false
  time-limit-exceed: 1000

